[pytest]
testpaths = tests
python_files = test_*.py

addopts = -v --html=reports/report.html --self-contained-html

log_cli = true
log_cli_level = INFO

log_file = reports/test.log
log_file_level = INFO

markers =
    saucedemo: SauceDemo application tests
    ui: UI automation tests
    smoke: Smoke tests
    regression: Regression tests